const fs = require('fs');
const dbPath = 'C:/Users/Osama/OneDrive/Documents/Obsidian Vault/Common/Product Requirements/UI-UX/flowna-react/public/db.json';
const db = JSON.parse(fs.readFileSync(dbPath, 'utf8'));

db.pm = {
  goals: [
    { id:'goal-zenith', title:'Close Zenith Enterprise Deal',   priority:'high',   status:'in-progress', progress:65, owner:'Osama', deadline:'2026-06-30', desc:'Sign and onboard Zenith Ltd as a paying enterprise customer at target ACV of EUR 120k.' },
    { id:'goal-flowna', title:'Launch Flowna v1.0',             priority:'high',   status:'in-progress', progress:40, owner:'Osama', deadline:'2026-09-01', desc:'Ship the first public version of Flowna — memory pipeline, agent orchestration, and onboarding flow.' },
    { id:'goal-scale',  title:'Scale Engineering Team to 8',    priority:'medium', status:'in-progress', progress:30, owner:'Omar',  deadline:'2026-08-01', desc:'Hire and onboard 4 additional engineers. Build interview process and onboarding playbook.' },
    { id:'goal-paper',  title:'Publish AI Research Paper',      priority:'low',    status:'not-started', progress:5,  owner:'Osama', deadline:'2026-12-01', desc:'Publish findings on temporal semantic graph embeddings for memory-augmented LLM agents.' },
  ],
  tasks: [
    { id:'t-1',  title:'Prepare BTNA negotiation deck',         goalId:'goal-zenith', assignee:'Osama', reporter:'Omar',  priority:'high',   status:'in-progress', dueDate:'2026-06-22', tags:['sales','negotiation'],       collaborators:[],          desc:'Build comprehensive negotiation deck with anchor strategy, ZOPA mapping, and concession schedule.', subtasks:[ {id:'st-1a',title:'Research Zenith BATNA alternatives',done:true}, {id:'st-1b',title:'Define anchor at EUR 120k',done:true}, {id:'st-1c',title:'Prepare concession schedule',done:false}, {id:'st-1d',title:'Role-play session with Omar',done:false} ] },
    { id:'t-2',  title:'Draft Zenith enterprise contract',      goalId:'goal-zenith', assignee:'Omar',  reporter:'Osama', priority:'medium', status:'todo',        dueDate:'2026-06-24', tags:['legal','sales'],             collaborators:['Osama'],   desc:'Draft contract with SLA clauses, payment terms, and data processing addendum.',              subtasks:[ {id:'st-2a',title:'SLA and uptime clauses',done:false}, {id:'st-2b',title:'Data processing addendum',done:false}, {id:'st-2c',title:'Legal review',done:false} ] },
    { id:'t-3',  title:'Final negotiation call prep',           goalId:'goal-zenith', assignee:'Osama', reporter:'Omar',  priority:'high',   status:'todo',        dueDate:'2026-06-25', tags:['sales'],                     collaborators:['Omar'],    desc:'Prepare talking points and objection responses for Thursday 14:00 close call.',              subtasks:[ {id:'st-3a',title:'Review final terms',done:true}, {id:'st-3b',title:'Rehearse objection handling',done:false}, {id:'st-3c',title:'Prepare fallback position',done:false} ] },
    { id:'t-4',  title:'Investor pitch — AI architecture',     goalId:'goal-zenith', assignee:'Osama', reporter:'Omar',  priority:'medium', status:'in-progress', dueDate:'2026-06-20', tags:['investors','product'],        collaborators:['Omar'],    desc:'4-slide section: retrieval pipeline, memory graph, agent orchestration, cost benchmarks.',    subtasks:[ {id:'st-4a',title:'Architecture diagram slide',done:true}, {id:'st-4b',title:'Pipeline demo recording',done:false}, {id:'st-4c',title:'Cost benchmarks slide',done:false}, {id:'st-4d',title:'Review with Omar',done:false} ] },
    { id:'t-5',  title:'Build memory pipeline v2',              goalId:'goal-flowna', assignee:'Osama', reporter:'Omar',  priority:'high',   status:'in-progress', dueDate:'2026-07-15', tags:['engineering','backend'],     collaborators:['Dina'],    desc:'Rewrite memory pipeline with idempotency, incremental re-analysis, and dead-letter queue.',  subtasks:[ {id:'st-5a',title:'Design schema and chunk contract',done:true}, {id:'st-5b',title:'Implement chunking layer',done:true}, {id:'st-5c',title:'Add idempotency tokens',done:true}, {id:'st-5d',title:'DLQ for failed inserts',done:false}, {id:'st-5e',title:'Integration tests',done:false} ] },
    { id:'t-6',  title:'Agent orchestration layer',             goalId:'goal-flowna', assignee:'Ali',   reporter:'Osama', priority:'high',   status:'review',      dueDate:'2026-07-10', tags:['engineering','agents'],      collaborators:['Osama'],   desc:'Core router that dispatches tasks to specialized agents and handles fallback chains.',         subtasks:[ {id:'st-6a',title:'API contract design',done:true}, {id:'st-6b',title:'Core router implementation',done:true}, {id:'st-6c',title:'Error and fallback chain',done:true}, {id:'st-6d',title:'Documentation',done:false} ] },
    { id:'t-7',  title:'User onboarding flow redesign',         goalId:'goal-flowna', assignee:'Sara',  reporter:'Omar',  priority:'medium', status:'in-progress', dueDate:'2026-07-20', tags:['product','ux'],              collaborators:[],          desc:'Redesign onboarding to reduce step-3 drop-off. Target: 80pct completion rate.',              subtasks:[ {id:'st-7a',title:'User research interviews',done:true}, {id:'st-7b',title:'Wireframes v1',done:true}, {id:'st-7c',title:'Clickable prototype',done:false}, {id:'st-7d',title:'Usability testing',done:false} ] },
    { id:'t-8',  title:'End-to-end test suite',                 goalId:'goal-flowna', assignee:'Dina',  reporter:'Osama', priority:'medium', status:'todo',        dueDate:'2026-08-01', tags:['engineering','testing'],     collaborators:[],          desc:'Full E2E coverage for onboarding, memory ingestion, and agent dispatch journeys.',            subtasks:[ {id:'st-8a',title:'Test plan document',done:false}, {id:'st-8b',title:'Write test cases',done:false}, {id:'st-8c',title:'CI integration',done:false} ] },
    { id:'t-9',  title:'Fix vector insert timeout',             goalId:'goal-flowna', assignee:'Dina',  reporter:'Osama', priority:'high',   status:'in-progress', dueDate:'2026-06-21', tags:['engineering','bug'],         collaborators:['Osama'],   desc:'Circuit breaker + exponential backoff for vector DB inserts timing out under load.',           subtasks:[ {id:'st-9a',title:'Reproduce under load test',done:true}, {id:'st-9b',title:'Root cause: missing timeout',done:true}, {id:'st-9c',title:'Implement circuit breaker',done:false}, {id:'st-9d',title:'Deploy hotfix',done:false} ] },
    { id:'t-10', title:'Async error handling RFC',              goalId:'goal-flowna', assignee:'Ali',   reporter:'Osama', priority:'medium', status:'blocked',     dueDate:'2026-07-05', tags:['engineering','standards'],   collaborators:['Osama'],   desc:'RFC for async error patterns across all services. Blocked on sign-off from Osama.',           subtasks:[ {id:'st-10a',title:'Research patterns',done:true}, {id:'st-10b',title:'Write RFC document',done:true}, {id:'st-10c',title:'Team review',done:false}, {id:'st-10d',title:'Merge and enforce',done:false} ] },
    { id:'t-11', title:'Branding update',                       goalId:'goal-flowna', assignee:'Sara',  reporter:'Omar',  priority:'low',    status:'done',        dueDate:'2026-06-10', tags:['design','brand'],            collaborators:[],          desc:'Updated logo, color tokens, and typography system applied across all surfaces.',               subtasks:[ {id:'st-11a',title:'Brand audit',done:true}, {id:'st-11b',title:'New asset creation',done:true}, {id:'st-11c',title:'Apply to product',done:true}, {id:'st-11d',title:'Slide template update',done:true} ] },
    { id:'t-12', title:'Write Frontend Engineer JD',            goalId:'goal-scale',  assignee:'Omar',  reporter:'Omar',  priority:'low',    status:'done',        dueDate:'2026-06-05', tags:['hiring'],                    collaborators:[],          desc:'Job description for senior frontend engineer. Posted on LinkedIn and AngelList.',              subtasks:[ {id:'st-12a',title:'Draft JD',done:true}, {id:'st-12b',title:'Review',done:true}, {id:'st-12c',title:'Post publicly',done:true} ] },
    { id:'t-13', title:'Interview process documentation',       goalId:'goal-scale',  assignee:'Omar',  reporter:'Omar',  priority:'low',    status:'done',        dueDate:'2026-06-08', tags:['hiring','process'],          collaborators:[],          desc:'3-stage interview process with scoring rubric and calibration guide.',                        subtasks:[ {id:'st-13a',title:'Define stages',done:true}, {id:'st-13b',title:'Scoring rubric',done:true}, {id:'st-13c',title:'Calibration guide',done:true} ] },
    { id:'t-14', title:'Engineering onboarding playbook',       goalId:'goal-scale',  assignee:'Ali',   reporter:'Omar',  priority:'low',    status:'in-progress', dueDate:'2026-07-01', tags:['hiring','process'],          collaborators:['Omar'],    desc:'Day-1 to day-30 guide for new engineers: setup, architecture, processes, and culture.',       subtasks:[ {id:'st-14a',title:'Gather content from team',done:true}, {id:'st-14b',title:'Write draft',done:false}, {id:'st-14c',title:'Review with Omar',done:false} ] },
    { id:'t-15', title:'Literature review — temporal graphs',   goalId:'goal-paper',  assignee:'Osama', reporter:'Osama', priority:'low',    status:'todo',        dueDate:'2026-08-15', tags:['research','ai'],             collaborators:[],          desc:'Review 20 papers on temporal semantic graphs and memory-augmented language models.',           subtasks:[ {id:'st-15a',title:'Collect candidate papers',done:false}, {id:'st-15b',title:'Read and annotate',done:false}, {id:'st-15c',title:'Synthesise findings',done:false} ] },
  ]
};

const srvPath = 'C:/Users/Osama/OneDrive/Documents/Obsidian Vault/Common/Product Requirements/UI-UX/flowna-react/src/api/server.js';
fs.writeFileSync(srvPath, fs.readFileSync(srvPath,'utf8').replace('flowna_db_v25','flowna_db_v26'));
fs.writeFileSync(dbPath, JSON.stringify(db, null, 2));
console.log('done v26');
