/* Shared, store-driven actions (mutate the simulated DB). */

export function runOneTap({ update, showToast }) {
  update((d) => {
    d.queue.columns.find((c) => c.id === "suggest").cards.push({
      id: "auto" + Date.now(), title: "Morning routine batch", agent: "@Mary", lane: "Ops",
      actions: ["Approve"], why: "Generated by One-Tap",
    });
  });
  showToast("⦿ Brain working… triage · draft · refresh · find gaps → staging");
  setTimeout(() => showToast("Done — 7 actions handled, 2 need you"), 2800);
}

export function queueAction({ update, showToast }, act, cardId) {
  if (act === "✎") { showToast("Opening draft to edit…"); return; }
  update((d) => {
    const cols = d.queue.columns;
    let card, from;
    for (const c of cols) { const i = c.cards.findIndex((x) => x.id === cardId); if (i >= 0) { card = c.cards[i]; from = c; } }
    if (!card) return;
    from.cards = from.cards.filter((x) => x.id !== cardId);
    card.actions = null; card.meta = act === "Send" ? "sent" : "approved";
    cols.find((c) => c.id === "done").cards.push(card);
  });
  showToast(`${act} → moved to Done`);
}
